// Array of special characters to be included in password
var specialCharacters = [
  '@',
  '%',
  '+',
  '\\',
  '/',
  "'",
  '!',
  '#',
  '$',
  '^',
  '?',
  ':',
  ',',
  ')',
  '(',
  '}',
  '{',
  ']',
  '[',
  '~',
  '-',
  '_',
  '.'
];

// Array of numeric characters to be included in password
var numericCharacters = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];

// Array of lowercase characters to be included in password
var lowerCasedCharacters = [
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'i',
  'j',
  'k',
  'l',
  'm',
  'n',
  'o',
  'p',
  'q',
  'r',
  's',
  't',
  'u',
  'v',
  'w',
  'x',
  'y',
  'z'
];

// Array of uppercase characters to be included in password
var upperCasedCharacters = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z'
];


// Code should validate for each input and at least one character type should be selected
// Once prompts are answered then the password should be generated and displayed in an alert or written to the page


// Write conditional statement if password length is less than 8 or more than 128 - error, user has to choose between 8 and 128.
//if no password options (cancel buttons ) are chosen alert the user that PASSWORD CAN'T BE GENERATED 

//ask user about password length and password option 
// Function to prompt user for password options
function getPasswordOptions() {
  let passwordLength = prompt("How many characters would you like your password to contain?");
  console.log("Good choice " + passwordLength);

  let lowerCase = confirm("If you wish your password contain Lowercase Letters press OK");
  let upperCase = confirm("If you wish your password contain Uppercase Letters press OK");
  let number = confirm("If you wish your password contain Numeric Characters press OK");
  let symbol = confirm("If you wish your password contain Special Characters press OK");

  //write a logic if YES ( true) if Cancel (false)


}

// Function for getting a random element from an array
// use random index and based on that choose one element and return it 
function getRandom(arr) {
  // Get the length of the array
  const length = arr.length;

  // Generate a random index
  const randomIndex = Math.floor(Math.random() * length);

  // Access the element at the random index
  const randomElement = arr[randomIndex];

  // Return the random element
  return randomElement;

}

var sym = getRandom(specialCharacters);
var upcase = getRandom(upperCasedCharacters);
var lowcase = getRandom(lowerCasedCharacters);
var numeric = getRandom(numericCharacters);

const allChars = sym + upcase + lowcase + numeric ;


// Function to generate password with user input
function generatePassword() {

  // let password = "";
//generate password based on what character types user chose and the number of characters
// while passwordLength chosen by user is greater than password generated by getRandom 
// password += allChars[Math.floor(Math.random() * allChars.length)];

 

}

// Get references to the #generate element
var generateBtn = document.querySelector('#generate');

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector('#password');

  passwordText.value = password;
}

// Add event listener to generate button
generateBtn.addEventListener('click', writePassword);